// Prototypes For Functions in TCPcontrolGUI.c which are not automatically generated by TCPcontrolGUI.uir
// Avoids Hassels this way

#define MAX_DDS_SCANRATE 100.0 //in MHz/ms (this is actually currently limited by the max laser scan response rate

int TCP_Comm_Callback(unsigned handle, int xType, int errCode, void *callbackData);
char* tcp_errorlookup(int tcp_error_code);
